version: '3.8'
services:
    client:
        container_name: client
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - .:/client
            - '/client/node_modules'
        environment:
            - CHOKIDAR_USEPOLLING=true
